name: saible_consulting_core
description: "Shared components for Saible Consulting plugins, including a comprehensive country list"
version: 0.1.0
repository: https://github.com/saible-app/saible_consulting
issue_tracker: https://github.com/saible-app/saible_consulting/issues

topics:
  - flutter
  - countries
  - localization
  - search
  - date

environment:
  sdk: ^3.13.2
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  material_ui: ^1.4.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  generate: true

resolution: workspace
